import '../css/landing.css'
import '../assets/three-guys.png'
import '../assets/download_links/app store.png'
import '../assets/download_links/app gallery.png'
import '../assets/download_links/google play.png'
import '../assets/phones/main phones/ph1.png'
import '../assets/phones/main phones/ph2.png'
import '../assets/decrations/head/arrow head phones 1.png'
import '../assets/decrations/head/arrow head phones 2.png'
import '../assets/decrations/head/vector head phones 1.png'
import '../assets/decrations/head/vector head phones 2.png'
import '../assets/blocks/Block 3.png'
import '../assets/blocks/Block 4.png'
import '../assets/blocks/Block 5.png'
import '../assets/blocks/Block 6.png'
import '../assets/buildings/Academy.png'
import '../assets/chibies/chibi clever.png'
import '../assets/blocks/academy/b-primary.png'
import '../assets/blocks/academy/b-primary.png'
import '../assets/blocks/academy/b-additive.png'