import '../css/landing.css'
import '../assets/three-guys.png'
import '../assets/download_links/app store.png'
import '../assets/download_links/app gallery.png'
import '../assets/download_links/google play.png'
import '../assets/phones/main phones/ph1.png'
import '../assets/phones/main phones/ph2.png'
import '../assets/decrations/head/arrow head phones 1.png'
import '../assets/decrations/head/arrow head phones 2.png'
import '../assets/decrations/head/vector head phones 1.png'
import '../assets/decrations/head/vector head phones 2.png'